"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const userController_1 = require("../controllers/userController");
const authMiddlware_1 = require("../middlwares/authMiddlware");
const router = (0, express_1.Router)();
router.post('/new', userController_1.registerUser);
router.put('/update', authMiddlware_1.protect, userController_1.updateUser);
router.post('/login', userController_1.loginUser);
router.post('/changePassword', userController_1.changeUserPassword);
router.delete('/:id', authMiddlware_1.protectForAdmin, userController_1.deleteUser);
exports.default = router;
