"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const userController_1 = require("../controllers/userController");
const authMiddlware_1 = require("../middlwares/authMiddlware");
const router = (0, express_1.Router)();
router.route('/new').post(userController_1.registerUser);
router.route('/update').put(authMiddlware_1.protect, userController_1.updateUser);
router.route('/newAdmin').post(authMiddlware_1.protectForAdmin, userController_1.addAdmin);
router.route('/login').post(userController_1.loginUser);
router.route('/changePassword').post(userController_1.changeUserPassword);
exports.default = router;
